JAVA_HOME:=/usr/lib/jvm/java-6-openjdk
#Under mingw, add: -D_JNI_IMPLEMENTATION
JNI_CFLAGS:=-I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux
#Under mingw, add: -Wl,--kill-at
JNI_LDFLAGS:=
TCL_CFLAGS:=-I/usr/include/tcl
TCL_LDFLAGS:=

AR:=ar
SWIG:=swig
CC:=gcc

LUA_CFLAGS:=-I/usr/include/lua5.1
LUA_LDFLAGS:=-llua5.1 -ldl
GSL_CFLAGS:=
GSL_LDFLAGS:=-lgsl -lgslcblas -lm

override CFLAGS+=--std=c99 -O0 -g -Wall

PREFIX:=$(shell pwd)/build
